### ISSUE TITLE
given example and test data are inconsistent and cause some valid solutions to fail.

### ISSUE THREAD

**Issue by dkintop** [learn-co-curriculum/ruby-enumerables-hash-practice-green-grocer-lab#2]
The given example includes a :count object, however the data that is passed in from the spec file does not. This ended up causing a TypeError:
       no implicit conversion of Symbol into Integer
in a method that functions as the examples state it should.

**Comment by sgharms** [comment]
@dkintop 
Based on the information here, we're going to have to start digging through the whole lab to understand the mechanics at fault here. Can you give us a single test that's breaking because of this?

**Comment by sgharms** [comment]
@dkintop I'm sufficiently convinced by your issues here (and my trouble in stepping through this lab) that we're going to do a rewrite here. Thanks for your insight.
